import-module ActiveDirectory

 

$Header = @"
<style>

    h1 {

        font-family: Arial, Helvetica, sans-serif;
        color: #e68a00;
        font-size: 28px;

    }

    
    h2 {

        font-family: Arial, Helvetica, sans-serif;
        color: #000099;
        font-size: 16px;

    }

    
    
   table {
		font-size: 12px;
		border: 0px; 
		font-family: Arial, Helvetica, sans-serif;
	} 
	
    td {
		padding: 4px;
		margin: 0px;
		border: 0;
	}
	
    th {
        background: #395870;
        background: linear-gradient(#49708f, #293f50);
        color: #fff;
        font-size: 11px;
        text-transform: uppercase;
        padding: 10px 15px;
        vertical-align: middle;
	}

    tbody tr:nth-child(even) {
        background: #f0f0f2;
    }
    


    #CreationDate {

        font-family: Arial, Helvetica, sans-serif;
        color: #ff3300;
        font-size: 12px;

    }



    .StopStatus {

        color: #ff0000;
    }
    
  
    .RunningStatus {

        color: #008000;
    }




</style>

"@

$User_Desc = Get-ADUser -Identity "Cpink" -Properties Description |
 Select-Object -ExpandProperty Description

$User_Name = Get-ADUser -Identity "Cpink" -Properties Name|
 Select-Object -ExpandProperty Name

 $User_Email = Get-ADUser -Identity "Cpink" -Properties EmailAddress|
 Select-Object -ExpandProperty EmailAddress

 $User_FullName = Get-ADUser -Identity "Cpink" -Properties DisplayName|
 Select-Object -ExpandProperty DisplayName

 $User_Department = Get-ADUser -Identity "Cpink" -Properties Department|
 Select-Object -ExpandProperty Department

$htmlParams = @{
    Head = $Header 
    Title = "This is Description"
    Body = "<h1>Generated by Corporate IT</h1>" + "<h2>Username: " + $User_Name + "</h2>"
    PostContent = "<h2>Email: " + $User_Email + "</h2>" +
    "<h2>Full Name: " + $User_FullName + "</h2>" +
    "<h2>Description: " + $User_Desc + "</h2>" +
    "<h2>Department: " + $User_Department + "</h2>"
  }
ConvertTo-Html @htmlParams |
Out-File Show-User-Description.html
 
Start-Process .\Show-User-Description.html  